const foods=[
  {id:'kebab',name:'Chicken Kebab',icon:'🌯',price:14,prep:1.2,station:'ROTISSERIE'},
  {id:'hsp',name:'HSP',icon:'🥙',price:18,prep:1.7,station:'HSP BENCH'},
  {id:'chips',name:'Hot Chips',icon:'🍟',price:7,prep:1,station:'FRYER'},
  {id:'falafel',name:'Falafel Roll',icon:'🧆',price:13,prep:1.4,station:'GRILL'}
];
const customerTypes=[
  {name:'Tradie',face:'👷',names:['Mick','Sam','Dylan'],orders:[['kebab'],['hsp'],['kebab','chips']],patience:24,tip:2},
  {name:'Uni student',face:'🧑‍🎓',names:['Aisha','Liam','Jess'],orders:[['hsp'],['chips'],['falafel']],patience:28,tip:1},
  {name:'Office worker',face:'👩‍💼',names:['Priya','Daniel','Sophie'],orders:[['kebab'],['falafel'],['hsp']],patience:20,tip:3},
  {name:'Footy fan',face:'🧑‍🦱',names:['Jack','Noah','Tahlia'],orders:[['hsp','chips'],['kebab','chips']],patience:23,tip:2}
];
const events=['FRIDAY NIGHT · SYDNEY','UNI NIGHT · LATE RUSH','FOOTY CROWD · EXTRA TIPS','RAINY NIGHT · DELIVERY SURGE'];
const upgrades=[
  {id:'rotisserie',name:'Hotter rotisserie',icon:'🔥',cost:80,desc:'Kebabs and falafel cook 25% faster.'},
  {id:'fryer',name:'Twin-basket fryer',icon:'🍟',cost:110,desc:'Chips and HSP prep 30% faster.'},
  {id:'seating',name:'Extra tables',icon:'🪑',cost:160,desc:'Serve one extra waiting customer.'}
];
const defaults={playing:false,time:90,money:0,wallet:0,lifetime:0,served:0,missed:0,tray:[],customers:[],spawn:0,golden:false,challenge:false,shift:1,profile:{shop:"Ikhwam's Kebabs",operator:'Ikhwam',apron:'red',hat:'cap',skin:'tan',theme:'red',glasses:false},upgrades:{rotisserie:false,fryer:false,seating:false}};
const $=id=>document.getElementById(id),food=id=>foods.find(f=>f.id===id);
function loadState(){try{const saved=JSON.parse(localStorage.getItem('kebabRushState')||'{}');return {...structuredClone(defaults),...saved,profile:{...defaults.profile,...saved.profile},upgrades:{...defaults.upgrades,...saved.upgrades},playing:false,challenge:false,customers:[],tray:[],money:0,time:90,served:0,missed:0,spawn:0,golden:false}}catch{return structuredClone(defaults)}}
let state=loadState();
function persist(){localStorage.setItem('kebabRushState',JSON.stringify({wallet:state.wallet,lifetime:state.lifetime,shift:state.shift,profile:state.profile,upgrades:state.upgrades}))}
function prepTime(f){let mult=1;if((f.id==='kebab'||f.id==='falafel')&&state.upgrades.rotisserie)mult*=.75;if((f.id==='chips'||f.id==='hsp')&&state.upgrades.fryer)mult*=.7;return f.prep*mult}
function venueLevel(){return state.lifetime>=2500?4:state.lifetime>=1200?3:state.lifetime>=550?2:state.lifetime>=180?1:0}
function applyProfile(){const p=state.profile;$('shopName').textContent=p.shop;$('operatorName').textContent=p.operator.toUpperCase();$('shopSign').className=`shop-sign theme-${p.theme}`;[$('operatorAvatar'),$('operatorPreview')].forEach(el=>{el.className=`${el.id==='operatorAvatar'?'operator-avatar':'operator-preview'} apron-${p.apron} hat-${p.hat} skin-${p.skin}${p.glasses?' has-glasses':''}`})}
function renderMenu(){$('menu').replaceChildren();foods.forEach(f=>{const b=document.createElement('button');b.className='food';const prep=prepTime(f);b.innerHTML=`<span>${f.icon}</span>${f.name}<small>$${f.price} · ${prep.toFixed(1)}s</small><em>${f.station}</em>`;b.disabled=!state.playing||state.challenge;b.onclick=()=>cook(f);$('menu').append(b)})}
function cook(f){if(!state.playing||state.challenge)return;if(state.tray.length>=3)return say('Bench full — serve somebody first!');say(`${f.name} on the ${f.station.toLowerCase()}…`);const duration=prepTime(f);setTimeout(()=>{if(!state.playing||state.challenge)return;state.tray.push(f.id);renderTray();say(`${f.name} ready!`)},duration*1000)}
function renderTray(){$('tray').textContent=state.tray.length?state.tray.map(x=>food(x).icon+' '+food(x).name).join(' · '):'Tap a station to prepare food'}
function spawn(){const cap=state.upgrades.seating?4:3;if(state.customers.length>=cap)return;const t=customerTypes[Math.floor(Math.random()*customerTypes.length)];let order=[...t.orders[Math.floor(Math.random()*t.orders.length)]];const gold=!state.golden&&state.served>=3&&state.time<68&&state.time>18&&Math.random()<.5;if(gold){state.golden=true;order=['golden']}state.customers.push({id:crypto.randomUUID(),type:t.name,name:t.names[Math.floor(Math.random()*t.names.length)],face:t.face,order,left:gold?38:t.patience,max:gold?38:t.patience,gold,tip:t.tip});renderCustomers()}
function renderCustomers(){$('customers').replaceChildren();state.customers.forEach((c,index)=>{const b=document.createElement('button');b.className='customer';b.style.setProperty('--y',`${index%2?10:0}px`);b.style.setProperty('--r',`${index%2?1.5:-1.5}deg`);const order=c.gold?'🏆 GOLDEN HSP':c.order.map(x=>food(x).icon).join(' ');b.innerHTML=`<div class="order">${order}</div><div class="face">${c.face}</div><small>${c.name} · ${c.type}</small><span class="patience"><i style="width:${Math.max(0,100*c.left/c.max)}%"></i></span>`;b.onclick=()=>serve(c);$('customers').append(b)})}
function sameOrder(a,b){return a.length===b.length&&[...a].sort().join('|')===[...b].sort().join('|')}
function serve(c){if(!state.playing||state.challenge)return;if(c.gold){startGolden(c);return}if(!sameOrder(c.order,state.tray))return say(state.tray.length?'Wrong order, boss — check the bench!':'Cook the order first, boss!');const base=c.order.reduce((s,x)=>s+food(x).price,0);const eventBonus=state.shift%3===0?1:0;const tip=c.left/c.max>.55?c.tip+eventBonus:0;state.money+=base+tip;state.served++;state.tray=[];state.customers=state.customers.filter(x=>x.id!==c.id);say(`Served ${c.name}! +$${base}${tip?` + $${tip} tip`:''}`);renderTray();renderCustomers();stats()}
function stats(){$('takings').textContent='$'+state.money;$('time').textContent=Math.max(0,Math.ceil(state.time))+'s';$('served').textContent=state.served;$('missed').textContent=state.missed+'/3';$('wallet').textContent='$'+state.wallet;$('level').textContent=venueLevel()+1;$('event').textContent=events[(state.shift-1)%events.length]}
function say(text){$('feedback').textContent=text}
function start(){if(state.playing)return;state.playing=true;state.challenge=false;state.time=90;state.money=0;state.served=0;state.missed=0;state.tray=[];state.customers=[];state.spawn=0;state.golden=false;$('start').disabled=true;$('customise').disabled=true;$('upgradesOpen').disabled=true;say(`Shift ${state.shift} open — Sydney is hungry.`);renderMenu();spawn();last=0;requestAnimationFrame(loop)}
let last=0;function loop(now){if(!state.playing)return;if(!last)last=now;const dt=Math.min(.1,(now-last)/1000);last=now;if(!state.challenge){state.time-=dt;state.spawn-=dt;state.customers.forEach(c=>c.left-=dt);const gone=state.customers.filter(c=>c.left<=0);if(gone.length){state.missed+=gone.length;state.customers=state.customers.filter(c=>c.left>0);say(`${gone.length} order${gone.length>1?'s':''} walked out!`)}if(state.spawn<=0){spawn();state.spawn=Math.max(2.7,6.8-state.served*.2)}renderCustomers();stats();if(state.time<=0||state.missed>=3)return end()}requestAnimationFrame(loop)}
function end(){state.playing=false;state.challenge=false;last=0;state.wallet+=state.money;state.lifetime+=state.money;state.shift++;persist();$('start').disabled=false;$('customise').disabled=false;$('upgradesOpen').disabled=false;$('start').textContent='NEXT SHIFT →';say(`Shift done · ${state.served} served · $${state.money} banked`);renderMenu();stats();renderUpgrades()}
let goldenCustomer=null,pulls=0,hits=0,phase=0,anim=0;function startGolden(c){goldenCustomer=c;state.challenge=true;$('golden').hidden=false;pulls=0;hits=0;$('sauceLines').replaceChildren();$('goldScore').textContent='Sauce pass 1 / 3';animateMeter()}
function animateMeter(){phase=(performance.now()/650)%2;const p=phase<=1?phase:2-phase;$('marker').style.left=(p*98)+'%';anim=requestAnimationFrame(animateMeter)}
$('pour').onclick=()=>{const p=parseFloat($('marker').style.left);pulls++;if(p>=40&&p<=60){hits++;const line=document.createElement('i');$('sauceLines').append(line)}if(pulls<3){$('goldScore').textContent=`Sauce pass ${pulls+1} / 3 · ${hits} clean`;return}cancelAnimationFrame(anim);$('golden').hidden=true;state.challenge=false;if(hits>=2){state.money+=30;state.served++;state.customers=state.customers.filter(x=>x.id!==goldenCustomer.id);say(`Golden HSP smashed! ${hits}/3 clean · +$30`)}else{goldenCustomer.gold=false;goldenCustomer.order=['hsp'];say('Close one — they’ll take a normal HSP.')}renderCustomers();renderMenu();stats()};
function openCustom(){const p=state.profile;$('shopNameInput').value=p.shop;$('operatorNameInput').value=p.operator;$('apronSelect').value=p.apron;$('hatSelect').value=p.hat;$('skinSelect').value=p.skin;$('themeSelect').value=p.theme;$('glassesCheck').checked=p.glasses;syncPreview();$('customOverlay').hidden=false}
function syncPreview(){const p={apron:$('apronSelect').value,hat:$('hatSelect').value,skin:$('skinSelect').value,glasses:$('glassesCheck').checked};$('operatorPreview').className=`operator-preview apron-${p.apron} hat-${p.hat} skin-${p.skin}${p.glasses?' has-glasses':''}`}
['apronSelect','hatSelect','skinSelect','themeSelect','glassesCheck'].forEach(id=>$(id).addEventListener('change',syncPreview));$('customise').onclick=openCustom;$('customClose').onclick=()=>{$('customOverlay').hidden=true};$('customForm').onsubmit=e=>{e.preventDefault();state.profile={shop:$('shopNameInput').value.trim()||defaults.profile.shop,operator:$('operatorNameInput').value.trim()||defaults.profile.operator,apron:$('apronSelect').value,hat:$('hatSelect').value,skin:$('skinSelect').value,theme:$('themeSelect').value,glasses:$('glassesCheck').checked};persist();applyProfile();$('customOverlay').hidden=true;say('Looking sharp. Your shop identity is saved.')};
function renderUpgrades(){$('upgradeWallet').textContent=`Available cash: $${state.wallet}`;$('upgradeList').replaceChildren();upgrades.forEach(u=>{const owned=state.upgrades[u.id];const card=document.createElement('div');card.className='upgrade-card'+(owned?' owned':'');card.innerHTML=`<span>${u.icon}</span><div><b>${u.name}</b><small>${u.desc}</small></div><button ${owned?'disabled':''}>${owned?'OWNED':'$'+u.cost}</button>`;card.querySelector('button').onclick=()=>buyUpgrade(u);$('upgradeList').append(card)})}
function buyUpgrade(u){if(state.upgrades[u.id])return;if(state.wallet<u.cost)return say(`Need $${u.cost-state.wallet} more for ${u.name}.`);state.wallet-=u.cost;state.upgrades[u.id]=true;persist();renderUpgrades();renderMenu();stats();say(`${u.name} installed. The shop just got better.`)}
$('upgradesOpen').onclick=()=>{renderUpgrades();$('upgradesOverlay').hidden=false};$('upgradesClose').onclick=()=>{$('upgradesOverlay').hidden=true};$('clear').onclick=()=>{if(state.challenge)return;state.tray=[];renderTray()};$('start').onclick=start;applyProfile();renderMenu();renderTray();renderCustomers();renderUpgrades();stats();