const ALLOWED_ORIGINS=new Set(['https://ikhwamnordin.github.io','http://localhost:5173','http://127.0.0.1:5173']);
const SESSION_DAYS=30;
const enc=new TextEncoder();
const json=(body,status=200,origin='')=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...cors(origin)}});
function cors(origin){return origin&&ALLOWED_ORIGINS.has(origin)?{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PUT,OPTIONS','access-control-allow-headers':'content-type,authorization','access-control-max-age':'86400','vary':'origin'}:{}};
function hex(bytes){return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bytesFromHex(value){const out=new Uint8Array(value.length/2);for(let i=0;i<out.length;i++)out[i]=parseInt(value.slice(i*2,i*2+2),16);return out}
function base64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha(value){return hex(await crypto.subtle.digest('SHA-256',enc.encode(value)))}
function token(){return base64url(crypto.getRandomValues(new Uint8Array(32)))}
function now(){return new Date().toISOString()}
function future(days){return new Date(Date.now()+days*86400000).toISOString()}
function cleanName(value,max=20){return typeof value==='string'?value.trim().replace(/\s+/g,' ').slice(0,max):''}
function cleanShop(value){return cleanName(value,32)||'Local Kebab Shop'}
function usernameNorm(value){return cleanName(value,20).toLowerCase()}
function validPin(value){return typeof value==='string'&&/^\d{4,12}$/.test(value)}
function safeInt(value,min,max){return Number.isInteger(value)&&value>=min&&value<=max}
async function pinHash(pin,saltHex){const key=await crypto.subtle.importKey('raw',enc.encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytesFromHex(saltHex),iterations:120000},key,256);return hex(bits)}
function equalHash(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function body(request,max=12000){const raw=await request.text();if(raw.length>max)throw new Error('PAYLOAD_TOO_LARGE');return JSON.parse(raw||'{}')}
async function session(request,env){const auth=request.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return null;const raw=auth.slice(7).trim();if(!raw)return null;const hash=await sha(raw);const row=await env.DB.prepare(`SELECT p.id,p.display_name,s.expires_at FROM sessions s JOIN players p ON p.id=s.player_id WHERE s.token_hash=?`).bind(hash).first();if(!row)return null;if(row.expires_at<=now()){await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(hash).run();return null}return {id:row.id,name:row.display_name,tokenHash:hash}}
async function issueSession(playerId,env){const raw=token(),hash=await sha(raw),created=now(),expires=future(SESSION_DAYS);await env.DB.prepare('INSERT INTO sessions(token_hash,player_id,created_at,expires_at) VALUES(?,?,?,?)').bind(hash,playerId,created,expires).run();return {token:raw,expiresAt:expires}}
function authRequired(origin){return json({error:'Sign in to continue.'},401,origin)}
async function register(request,env,origin){const data=await body(request);const display=cleanName(data.name),norm=usernameNorm(data.name),pin=data.pin;if(display.length<3||norm.length<3)return json({error:'Player name must be at least 3 characters.'},400,origin);if(!validPin(pin))return json({error:'PIN must be 4–12 digits.'},400,origin);const exists=await env.DB.prepare('SELECT 1 FROM players WHERE username_norm=?').bind(norm).first();if(exists)return json({error:'That player name is already registered.'},409,origin);const salt=hex(crypto.getRandomValues(new Uint8Array(16))),hash=await pinHash(pin,salt),id=crypto.randomUUID(),stamp=now();await env.DB.prepare('INSERT INTO players(id,username_norm,display_name,pin_salt,pin_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,norm,display,salt,hash,stamp,stamp).run();const auth=await issueSession(id,env);return json({player:{id,name:display},...auth},201,origin)}
async function login(request,env,origin){const data=await body(request),norm=usernameNorm(data.name),pin=data.pin;if(!norm||!validPin(pin))return json({error:'Enter your player name and PIN.'},400,origin);const row=await env.DB.prepare('SELECT id,display_name,pin_salt,pin_hash FROM players WHERE username_norm=?').bind(norm).first();if(!row)return json({error:'Player name or PIN is incorrect.'},401,origin);const calculated=await pinHash(pin,row.pin_salt);if(!equalHash(calculated,row.pin_hash))return json({error:'Player name or PIN is incorrect.'},401,origin);const auth=await issueSession(row.id,env);return json({player:{id:row.id,name:row.display_name},...auth},200,origin)}
async function logout(request,env,origin){const current=await session(request,env);if(current)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(current.tokenHash).run();return json({ok:true},200,origin)}
async function me(request,env,origin){const current=await session(request,env);if(!current)return authRequired(origin);return json({player:{id:current.id,name:current.name}},200,origin)}
async function postScore(request,env,origin){const current=await session(request,env);if(!current)return authRequired(origin);const data=await body(request);if(!safeInt(data.takings,0,2500)||!safeInt(data.served,0,80)||!safeInt(data.missed,0,3)||!safeInt(data.shift,1,100000))return json({error:'Invalid score payload.'},400,origin);const shop=cleanShop(data.shop);const id=crypto.randomUUID(),stamp=now();await env.DB.prepare('INSERT INTO scores(id,player_id,shop,takings,served,missed,shift_no,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,current.id,shop,data.takings,data.served,data.missed,data.shift,stamp).run();return json({ok:true,id},201,origin)}
async function leaderboard(request,env,origin){const url=new URL(request.url);const limit=Math.min(50,Math.max(10,Number(url.searchParams.get('limit'))||25));const current=await session(request,env);const query=`WITH best AS (SELECT s.*,ROW_NUMBER() OVER(PARTITION BY player_id ORDER BY takings DESC,served DESC,created_at ASC) rn FROM scores s), ranked AS (SELECT b.player_id,p.display_name AS player,b.shop,b.takings,b.served,b.created_at,RANK() OVER(ORDER BY b.takings DESC,b.served DESC,b.created_at ASC) AS rank FROM best b JOIN players p ON p.id=b.player_id WHERE b.rn=1) SELECT rank,player,shop,takings,served,created_at,player_id=? AS isYou FROM ranked ORDER BY rank,player LIMIT ?`;const result=await env.DB.prepare(query).bind(current?.id||'',limit).all();let mine=null;if(current){mine=await env.DB.prepare(`WITH best AS (SELECT s.*,ROW_NUMBER() OVER(PARTITION BY player_id ORDER BY takings DESC,served DESC,created_at ASC) rn FROM scores s), ranked AS (SELECT b.player_id,p.display_name AS player,b.shop,b.takings,b.served,RANK() OVER(ORDER BY b.takings DESC,b.served DESC,b.created_at ASC) AS rank FROM best b JOIN players p ON p.id=b.player_id WHERE b.rn=1) SELECT rank,player,shop,takings,served FROM ranked WHERE player_id=?`).bind(current.id).first()}return json({entries:result.results||[],mine,updatedAt:now()},200,origin)}
async function getProgress(request,env,origin){const current=await session(request,env);if(!current)return authRequired(origin);const row=await env.DB.prepare('SELECT state,revision,updated_at FROM progress WHERE player_id=?').bind(current.id).first();return json(row?{state:JSON.parse(row.state),revision:row.revision,updatedAt:row.updated_at}:{state:null,revision:0,updatedAt:null},200,origin)}
function validProgress(s){return s&&safeInt(s.wallet,0,1e9)&&safeInt(s.lifetime,0,1e9)&&safeInt(s.shift,1,100000)&&s.profile&&typeof s.profile.shop==='string'&&s.profile.shop.length<=32&&typeof s.profile.operator==='string'&&s.profile.operator.length<=20&&s.upgrades&&['rotisserie','fryer','seating'].every(k=>typeof s.upgrades[k]==='boolean')}
async function putProgress(request,env,origin){const current=await session(request,env);if(!current)return authRequired(origin);const data=await body(request,20000);if(!validProgress(data.state)||!safeInt(data.revision,0,1e9))return json({error:'Invalid progress payload.'},400,origin);const stamp=now(),state=JSON.stringify(data.state);if(data.revision===0){const existing=await env.DB.prepare('SELECT revision FROM progress WHERE player_id=?').bind(current.id).first();if(!existing){await env.DB.prepare('INSERT INTO progress(player_id,state,revision,updated_at) VALUES(?,?,1,?)').bind(current.id,state,stamp).run();return json({revision:1,updatedAt:stamp},200,origin)}}const result=await env.DB.prepare('UPDATE progress SET state=?,revision=revision+1,updated_at=? WHERE player_id=? AND revision=?').bind(state,stamp,current.id,data.revision).run();if(result.meta.changes)return json({revision:data.revision+1,updatedAt:stamp},200,origin);return json({error:'Cloud progress changed elsewhere. Reload before saving again.'},409,origin)}
export default {async fetch(request,env){const origin=request.headers.get('origin')||'';if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(origin&&!ALLOWED_ORIGINS.has(origin))return json({error:'Origin not allowed.'},403,'');try{if(!env.DB)return json({error:'Database unavailable.'},503,origin);const {pathname}=new URL(request.url);if(pathname==='/health'&&request.method==='GET')return json({ok:true,service:'kebab-rush-api'},200,origin);if(pathname==='/v1/register'&&request.method==='POST')return register(request,env,origin);if(pathname==='/v1/login'&&request.method==='POST')return login(request,env,origin);if(pathname==='/v1/logout'&&request.method==='POST')return logout(request,env,origin);if(pathname==='/v1/me'&&request.method==='GET')return me(request,env,origin);if(pathname==='/v1/scores'&&request.method==='POST')return postScore(request,env,origin);if(pathname==='/v1/leaderboard'&&request.method==='GET')return leaderboard(request,env,origin);if(pathname==='/v1/progress'&&request.method==='GET')return getProgress(request,env,origin);if(pathname==='/v1/progress'&&request.method==='PUT')return putProgress(request,env,origin);return json({error:'Not found.'},404,origin)}catch(error){console.error(error);const message=error?.message==='PAYLOAD_TOO_LARGE'?'Payload too large.':'Server error.';return json({error:message},error?.message==='PAYLOAD_TOO_LARGE'?413:500,origin)}}};
